#!/bin/bash

# Copyright Anand Jain <asj@kernel.org>
# GLPv3

# https://www.kernel.org/doc/Documentation/block/stat.txt

#read I/Os       requests      number of read I/Os processed
#read merges     requests      number of read I/Os merged with in-queue I/O
#read sectors    sectors       number of sectors read
#read ticks      milliseconds  total wait time for read requests
#write I/Os      requests      number of write I/Os processed
#write merges    requests      number of write I/Os merged with in-queue I/O
#write sectors   sectors       number of sectors written
#write ticks     milliseconds  total wait time for write requests
#in_flight       requests      number of I/Os currently in flight
#io_ticks        milliseconds  total time this block device has been active
#time_in_queue   milliseconds  total wait time for all requests
#discard I/Os    requests      number of discard I/Os processed
#discard merges  requests      number of discard I/Os merged with in-queue I/O
#discard sectors sectors       number of sectors discarded

#example:
# $ devstat sda sdb
#read[ios   merges sectos     wait]   write[ios  merges sectos      wait] inflight  rw[active   wait] discard[ios   merges   sectors  wait] flush[ios   wait]
#   40129        4   599864   119494     1235    13938   130888       74        0   121213   119569        0        0        0        0        0        0
# 2135372        0 17198073   219849    17744     2050  4249568   371763        0   242283   591612        0        0        0        0        0        0


echo "read[ios   merges sectors     wait]   write[ios  merges sectos      wait] inflight  rw[active   wait] discard[ios   merges   sectors  wait] flush[ios   wait]"
for dev in $@
do
	tmp=$(echo "$dev" | rev | cut -d"/" -f1 | rev)
	echo -n $tmp" "
	cat $(find /sys -name stat | grep $tmp)
done
